In [1]:
from perceptron import Perceptron

In [2]:
import numpy as np

**Conjunto de Datos AND**

In [3]:
X = np.array([[1,1,1],[1,1,0],[1,0,1],[1,0,0],[0,1,1],[0,1,0],[0,0,1],[0,0,0]])
X

array([[1, 1, 1],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0],
       [0, 1, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [4]:
X.shape

(8, 3)

In [5]:
y = np.array([[1],[0],[0],[0],[0],[0],[0],[0]])
y

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

**Definición del perceptrón y entrenamiento**

In [9]:
p = Perceptron(X.shape[1],alpha=0.1)

In [10]:
p.fit(X,y,epochs=20)

**Iteramos sobre el conjunto de datos y hacemos las predicciones**

In [11]:
for (x,salida) in zip(X,y):
    prediccion = p.predict(x)
    print("entradas={}, salida-deseada={}, prediccion={}".format(
    x,salida[0],prediccion))

entradas=[1 1 1], salida-deseada=1, prediccion=1
entradas=[1 1 0], salida-deseada=0, prediccion=0
entradas=[1 0 1], salida-deseada=0, prediccion=0
entradas=[1 0 0], salida-deseada=0, prediccion=0
entradas=[0 1 1], salida-deseada=0, prediccion=0
entradas=[0 1 0], salida-deseada=0, prediccion=0
entradas=[0 0 1], salida-deseada=0, prediccion=0
entradas=[0 0 0], salida-deseada=0, prediccion=0


In [12]:
p.pesos()

[ 0.11279114  0.20869189  0.26428391 -0.56769635]


In [13]:
def andEntrenado(x1,x2,x3):
    y = x1*0.11202201+x2*0.20394316+x3*0.26428391+1*(-0.56769635)
    if y>0: 
        return 1
    else:
        return 0

In [14]:
andEntrenado(1,1,1)

1

In [15]:
andEntrenado(0,1,1)

0

In [16]:
andEntrenado(0,0,0)

0